# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirbnbApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for AirbnbApp

  target 'AirbnbApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  #  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

   # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'AirbnbAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end